### ISSUE TITLE
Amazon Linux AMI support

### ISSUE THREAD

**Issue by 1tayH** [lief-project/LIEF#103]
Hi,
I'm trying to get LIEF to work on an AWS Lambda function (which is based on Amazon Linux). It installs just fine using pip, however, I'm getting this error when trying to import it:
```
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/lib64/python2.7/site-packages/_pylief.so)

```

It appears to happen because Amazon Linux's libstdc++.so.6 is a bit too old:
```
$ strings /usr/lib64/libstdc++.so.6 | grep "GLIBCXX"
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

``` 

Any help, suggestions on how to proceed would be highly appreciated.

**Comment by romainthomas** [comment]
I think its related to #26 You can use this Dockerfile: https://github.com/lief-project/Dockerlief/blob/master/dockerlief/dockerfiles/centos.docker to build a compliant package.

**Comment by 1tayH** [comment]
@romainthomas Thanks for the reply, while it does seem like it's related to #26, the dockerfile fails:
```
[ 54%] Built target LIB_LIEF_STATIC
make: *** [all] Error 2
The command '/bin/sh -c make -j3' returned a non-zero code: 2
```
the complete output: https://gist.github.com/1tayH/c9e525da777653f659edf07799c91577

**Comment by romainthomas** [comment]
it seems you don't have enough RAM: 

> virtual memory exhausted: Cannot allocate memory

**Comment by 1tayH** [comment]
@romainthomas Nice catch.
I'm getting another error now, not sure if I'm doing anything wrong:
```
$ sudo docker build -f centos.docker .
...
...
...
...
CPack3: - package: /tmp/LIEF/LIEF/build/LIEF-0.7.0-Linux.tar.gz generated.
 ---> de949589f375
Removing intermediate container bd7ba50efb63
Successfully built de949589f375

$ sudo docker run -i -t -d de949589f375 /bin/bash
331af9ade4a59a36f40dc023d40c0f7df33d35b438e04b187b141485c032f149

$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
331af9ade4a5        de949589f375        "/bin/bash"         23 seconds ago      Up 22 seconds                           determined_galileo

$ sudo docker cp 331af9ade4a5:/tmp/LIEF/LIEF/build/api/python .

$ cd python

$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing lief.egg-info/PKG-INFO
writing top-level names to lief.egg-info/top_level.txt
writing dependency_links to lief.egg-info/dependency_links.txt
reading manifest file 'lief.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lief.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/lief
copying lief/__init__.py -> build/lib.linux-x86_64-2.7/lief
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/_pylief.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/lief
copying build/lib.linux-x86_64-2.7/lief/__init__.py -> build/bdist.linux-x86_64/egg/lief
byte-compiling build/bdist.linux-x86_64/egg/lief/__init__.py to __init__.pyc
creating stub loader for _pylief.so
byte-compiling build/bdist.linux-x86_64/egg/_pylief.py to _pylief.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying lief.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lief.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lief.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lief.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lief.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/lief-0.7.0-py2.7-linux.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing lief-0.7.0-py2.7-linux.egg
Copying lief-0.7.0-py2.7-linux.egg to /usr/local/lib64/python2.7/site-packages
Adding lief 0.7.0 to easy-install.pth file
Installed /usr/local/lib64/python2.7/site-packages/lief-0.7.0-py2.7-linux.egg
Processing dependencies for lief==0.7.0
Finished processing dependencies for lief==0.7.0

$ python
Python 2.7.12 (default, Sep  1 2016, 22:14:00) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lief/__init__.py", line 4, in <module>
    import _pylief
ImportError: lief/_pylief.so: undefined symbol: PyInstanceMethod_Type

```

Any suggestions?

**Comment by romainthomas** [comment]
Use ``python3``

**Comment by 1tayH** [comment]
```
$ python34 
Python 3.4.3 (default, Sep  1 2016, 23:33:38) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/python/lief/__init__.py", line 4, in <module>
    import _pylief
ImportError: /home/ec2-user/python/_pylief.so: undefined symbol: _PyThreadState_UncheckedGet
```

**Comment by romainthomas** [comment]
You should use the same version as the docker version (``python35u-devel``) or change the Docker Python version according to you version

**Comment by 1tayH** [comment]
Does it have to be the exact same version? I'm running 3.5.1 on the host machine and 3.5.4 on the container:
```
$ sudo yum install python35-devel.x86_64 -y

...
Dependency Installed:
  python35.x86_64 0:3.5.1-13.7.amzn1                                                                                           python35-libs.x86_64 0:3.5.1-13.7.amzn1                                                                                          

Complete!

$ python35
Python 3.5.1 (default, Sep 13 2016, 18:48:37) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/python/lief/__init__.py", line 4, in <module>
    import _pylief
ImportError: /home/ec2-user/python/_pylief.so: undefined symbol: _PyThreadState_UncheckedGet

```

**Comment by romainthomas** [comment]
No Major.Minor ( ``3.5``) should be enough. 
It seems related to https://github.com/cython/cython/issues/1880
