### ISSUE TITLE
Failure to build from source using Python instructions

### ISSUE THREAD

**Issue by fanquake** [lief-project/LIEF#1037]
**Describe the bug**
Issue installing using the Python install instructions (https://lief.re/doc/latest/installation.html#python):
```bash
  × Building wheel for lief (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      LIEF Version: 0.15.0.dev0
      2024-03-22 10:18:42,401 - scikit_build_core - INFO - RUN: /usr/bin/cmake3 --version
      2024-03-22 10:18:42,417 - scikit_build_core - INFO - CMake version: 3.28.3
      *** scikit-build-core 0.8.1 using CMake 3.28.3 (wheel)
      2024-03-22 10:18:42,425 - scikit_build_core - INFO - Build directory: /tmp/tmpu6sn7dm5/build
      2024-03-22 10:18:42,426 - scikit_build_core - WARNING - No license files found, set wheel.license-files to [] to suppress this warning
      *** Configuring CMake...
      2024-03-22 10:18:42,430 - scikit_build_core - DEBUG - SITE_PACKAGES: /root/env/lib/python3.12/site-packages
      2024-03-22 10:18:42,430 - scikit_build_core - DEBUG - Extra SITE_PACKAGES: /root/env/lib/python3.12/site-packages
      2024-03-22 10:18:42,430 - scikit_build_core - DEBUG - Set generator: Ninja
      2024-03-22 10:18:42,431 - scikit_build_core - INFO - RUN: /root/env/bin/ninja --version
      Traceback (most recent call last):
        File "/root/env/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/env/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/env/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/LIEF/api/python/backend/setup.py", line 138, in build_wheel
          return _impl(wheel_directory, config_settings, metadata_directory)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7460zbpt/normal/lib/python3.12/site-packages/scikit_build_core/build/__init__.py", line 31, in build_wheel
          return _build_wheel_impl(
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7460zbpt/normal/lib/python3.12/site-packages/scikit_build_core/build/wheel.py", line 302, in _build_wheel_impl
          builder.configure(
        File "/tmp/pip-build-env-7460zbpt/normal/lib/python3.12/site-packages/scikit_build_core/builder/builder.py", line 146, in configure
          local_def = set_environment_for_gen(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7460zbpt/normal/lib/python3.12/site-packages/scikit_build_core/builder/generator.py", line 119, in set_environment_for_gen
          raise NinjaNotFoundError(msg)
      scikit_build_core.errors.NinjaNotFoundError: Ninja is required to build
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lief
Failed to build lief
ERROR: Could not build wheels for lief, which is required to install pyproject.toml-based projects
```

**To Reproduce**
```bash
git clone https://github.com/lief-project/LIEF

python -m venv env

source env/bin/activate

pip install -r LIEF/api/python/build-requirements.txt 
Collecting tomli==2.0.1 (from -r LIEF/api/python/build-requirements.txt (line 1))
  Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
Collecting scikit-build-core==0.8.1 (from -r LIEF/api/python/build-requirements.txt (line 2))
  Using cached scikit_build_core-0.8.1-py3-none-any.whl.metadata (19 kB)
Collecting setuptools==69.1.0 (from -r LIEF/api/python/build-requirements.txt (line 4))
  Using cached setuptools-69.1.0-py3-none-any.whl.metadata (6.1 kB)
Collecting pydantic==2.6.1 (from -r LIEF/api/python/build-requirements.txt (line 6))
  Using cached pydantic-2.6.1-py3-none-any.whl.metadata (83 kB)
Collecting pydantic-core==2.16.2 (from -r LIEF/api/python/build-requirements.txt (line 7))
  Using cached pydantic_core-2.16.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.5 kB)
Collecting pyproject_metadata==0.7.1 (from -r LIEF/api/python/build-requirements.txt (line 9))
  Using cached pyproject_metadata-0.7.1-py3-none-any.whl.metadata (3.0 kB)
Collecting pathspec==0.12.1 (from -r LIEF/api/python/build-requirements.txt (line 10))
  Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Collecting build==1.0.3 (from -r LIEF/api/python/build-requirements.txt (line 11))
  Using cached build-1.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting wheel==0.42.0 (from -r LIEF/api/python/build-requirements.txt (line 12))
  Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
Collecting packaging>=20.9 (from scikit-build-core==0.8.1->-r LIEF/api/python/build-requirements.txt (line 2))
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting annotated-types>=0.4.0 (from pydantic==2.6.1->-r LIEF/api/python/build-requirements.txt (line 6))
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting typing-extensions>=4.6.1 (from pydantic==2.6.1->-r LIEF/api/python/build-requirements.txt (line 6))
  Using cached typing_extensions-4.10.0-py3-none-any.whl.metadata (3.0 kB)
Collecting pyproject_hooks (from build==1.0.3->-r LIEF/api/python/build-requirements.txt (line 11))
  Using cached pyproject_hooks-1.0.0-py3-none-any.whl.metadata (1.3 kB)
Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Using cached scikit_build_core-0.8.1-py3-none-any.whl (139 kB)
Using cached setuptools-69.1.0-py3-none-any.whl (819 kB)
Using cached pydantic-2.6.1-py3-none-any.whl (394 kB)
Using cached pydantic_core-2.16.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.9 MB)
Using cached pyproject_metadata-0.7.1-py3-none-any.whl (7.4 kB)
Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
Using cached build-1.0.3-py3-none-any.whl (18 kB)
Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached packaging-24.0-py3-none-any.whl (53 kB)
Using cached typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Using cached pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)
Installing collected packages: wheel, typing-extensions, tomli, setuptools, pyproject_hooks, pathspec, packaging, annotated-types, scikit-build-core, pyproject_metadata, pydantic-core, build, pydantic
Successfully installed annotated-types-0.6.0 build-1.0.3 packaging-24.0 pathspec-0.12.1 pydantic-2.6.1 pydantic-core-2.16.2 pyproject_hooks-1.0.0 pyproject_metadata-0.7.1 scikit-build-core-0.8.1 setuptools-69.1.0 tomli-2.0.1 typing-extensions-4.10.0 wheel-0.42.0

pip install LIEF/api/python
Processing ./LIEF/api/python
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: lief
  Building wheel for lief (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for lief (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      LIEF Version: 0.15.0.dev0
      2024-03-22 10:21:40,943 - scikit_build_core - INFO - RUN: /usr/bin/cmake3 --version
      2024-03-22 10:21:40,958 - scikit_build_core - INFO - CMake version: 3.28.3
      *** scikit-build-core 0.8.1 using CMake 3.28.3 (wheel)
      2024-03-22 10:21:40,966 - scikit_build_core - INFO - Build directory: /tmp/tmp3wvzcnz4/build
      2024-03-22 10:21:40,967 - scikit_build_core - WARNING - No license files found, set wheel.license-files to [] to suppress this warning
      *** Configuring CMake...
      2024-03-22 10:21:40,972 - scikit_build_core - DEBUG - SITE_PACKAGES: /root/env/lib/python3.12/site-packages
      2024-03-22 10:21:40,972 - scikit_build_core - DEBUG - Extra SITE_PACKAGES: /root/env/lib/python3.12/site-packages
      2024-03-22 10:21:40,972 - scikit_build_core - DEBUG - Set generator: Ninja
      2024-03-22 10:21:40,972 - scikit_build_core - INFO - RUN: /usr/local/bin/ninja --version
      Traceback (most recent call last):
        File "/root/env/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/env/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/env/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/LIEF/api/python/backend/setup.py", line 138, in build_wheel
          return _impl(wheel_directory, config_settings, metadata_directory)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-3hozgk3e/normal/lib/python3.12/site-packages/scikit_build_core/build/__init__.py", line 31, in build_wheel
          return _build_wheel_impl(
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-3hozgk3e/normal/lib/python3.12/site-packages/scikit_build_core/build/wheel.py", line 302, in _build_wheel_impl
          builder.configure(
        File "/tmp/pip-build-env-3hozgk3e/normal/lib/python3.12/site-packages/scikit_build_core/builder/builder.py", line 146, in configure
          local_def = set_environment_for_gen(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-3hozgk3e/normal/lib/python3.12/site-packages/scikit_build_core/builder/generator.py", line 119, in set_environment_for_gen
          raise NinjaNotFoundError(msg)
      scikit_build_core.errors.NinjaNotFoundError: Ninja is required to build
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lief
Failed to build lief
ERROR: Could not build wheels for lief, which is required to install pyproject.toml-based projects
```

It seems to think that Ninja is not installed, as running `/usr/local/bin/ninja --version` fails, but it is installed:
```bash
# /usr/local/bin/ninja --version
1.11.1.git.kitware.jobserver-1
```

**Environment (please complete the following information):**
 - System and Version : aarch64 Fedora (Rawhde)
 - LIEF commit version: master (6dbb551af336fc5eaad85ee856aa18593e85ca49)
 - Python 3.12.2

**Comment by romainthomas** [comment]
`ninja` should be resolvable given the `PATH` environment variable. Maybe you should do:

```bash
export PATH=/usr/local/bin/:$PATH
pip install LIEF/api/python
```

**Comment by fanquake** [comment]
> Maybe you should do:

Thanks. `/usr/local/bin/` is already in my `$PATH`, so the above suggestion has not made a difference. However I have solved this now. `ninja` was available from somwhere else, but the system `ninja-build` pacakge was not actually installed, installing that now seems to have resolved all issues. Its not exactly clear to me why this should make a difference, but that is also an upstream issue.
