### ISSUE TITLE
installed by pip missing many attributes

### ISSUE THREAD

**Issue by yifengchen-cc** [lief-project/LIEF#1044]
**Describe the bug**
I tried to write the code following the samples in the /tests/ directory（https://github.com/lief-project/LIEF/blob/master/tests/elf/test_sectionless.py#L4）, but many attributes are different. How to completely and correctly install the python version of lief?

**To Reproduce**

```
$ sudo pip install lief
$ python3
Python 3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
>>> lief.ELF.Relocation.TYPE.X86_64_RELATIVE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Relocation' has no attribute 'TYPE'
>>> dir(lief.ELF.Relocation)
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'addend', 'address', 'has_section', 'has_symbol', 'info', 'is_rel', 'is_rela', 'purpose', 'section', 'size', 'symbol', 'symbol_table', 'type']
>>> lief.ELF.ParseConfig()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'lief._lief.ELF' has no attribute 'ParseConfig'. Did you mean: 'ParserConfig'?
>>>
```

**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 20.04]

 - Target format  ELF 

 - LIEF commit version: 

   ```
   $ python3 -c "import lief;print(lief.__version__)"
   0.14.1-bae887e0
   ```

**Comment by romainthomas** [comment]
Yep you are using the wrong version for the test. You can checkout the test on the `0.14.1` tag
