### ISSUE TITLE
pip3 install lief fails on Python 3.6/Cygwin

### ISSUE THREAD

**Issue by kornos** [lief-project/LIEF#113]
$ pip3 list |grep setuptools
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
setuptools (34.3.2)

$ pip3 install lief
Collecting lief
  Downloading lief-0.8.3.post2.zip
Building wheels for collected packages: lief
  Running setup.py bdist_wheel for lief ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/c/Users/xxx/AppData/Local/Temp/pip-build-pi1tleg0/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /c/Users/xxx/AppData/Local/Temp/tmp_f_c5wcppip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.cygwin-2.9.0-x86_64-3.6
  creating build/lib.cygwin-2.9.0-x86_64-3.6/lief
  copying lief/__init__.py -> build/lib.cygwin-2.9.0-x86_64-3.6/lief
  running build_ext
  Url: https://github.com/lief-project/LIEF/releases/download/0.8.3/lief-0.8.3-py3.6-None.egg
  HTTP Error 404: Not Found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/c/Users/xxx/AppData/Local/Temp/pip-build-pi1tleg0/lief/setup.py", line 281, in <module>
      'sdist':     lief_sdist
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 199, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
      _build_ext.run(self)
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/c/Users/xxx/AppData/Local/Temp/pip-build-pi1tleg0/lief/setup.py", line 211, in build_extension
      self._install_from_source_package()
    File "/c/Users/xxx/AppData/Local/Temp/pip-build-pi1tleg0/lief/setup.py", line 261, in _install_from_source_package
      raise Exception("Unable to find {}".format(url))
  Exception: Unable to find /c/Users/xxx/lief-0.8.3-py3.6-None.egg

  ----------------------------------------
  Failed building wheel for lief
  Running setup.py clean for lief
Failed to build lief
Installing collected packages: lief
  Running setup.py install for lief ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/c/Users/xxx/AppData/Local/Temp/pip-build-pi1tleg0/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /c/Users/xxx/AppData/Local/Temp/pip-fmzfcd8b-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.cygwin-2.9.0-x86_64-3.6
    creating build/lib.cygwin-2.9.0-x86_64-3.6/lief
    copying lief/__init__.py -> build/lib.cygwin-2.9.0-x86_64-3.6/lief
    running build_ext
    Url: https://github.com/lief-project/LIEF/releases/download/0.8.3/lief-0.8.3-py3.6-None.egg
    HTTP Error 404: Not Found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/c/Users/xxx/AppData/Local/Temp/pip-build-pi1tleg0/lief/setup.py", line 281, in <module>
        'sdist':     lief_sdist
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/c/Users/xxx/AppData/Local/Temp/pip-build-pi1tleg0/lief/setup.py", line 211, in build_extension
        self._install_from_source_package()
      File "/c/Users/xxx/AppData/Local/Temp/pip-build-pi1tleg0/lief/setup.py", line 261, in _install_from_source_package
        raise Exception("Unable to find {}".format(url))
    Exception: Unable to find /c/Users/xxx/lief-0.8.3-py3.6-None.egg

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/c/Users/XXX/AppData/Local/Temp/pip-build-pi1tleg0/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /c/Users/xxx/AppData/Local/Temp/pip-fmzfcd8b-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /c/Users/xxx/AppData/Local/Temp/pip-build-pi1tleg0/lief/

**Comment by romainthomas** [comment]
Actually LIEF packages are not provided for cygwin

**Comment by kornos** [comment]
Installing py packages should work by default in Cygwin.

I tried now on Ubuntu  and same error:

$ pip3 list|grep setuptools
setuptools (36.6.0)

$ pip3  install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.8.3.dev.zip
Downloading/unpacking https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.8.3.dev.zip
  Downloading pylief-0.8.3.dev.zip
  Running setup.py (path:/tmp/pip-oqesdw3p-build/setup.py) egg_info for package from https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.8.3.dev.zip
Installing collected packages: lief
  Running setup.py install for lief
    Url: https://github.com/lief-project/packages/raw/lief-master-latest/lief-0.8.3-py3.4-linux.egg
    HTTP Error 404: Not Found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-oqesdw3p-build/setup.py", line 281, in <module>
        'sdist':     lief_sdist
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/xxx/.local/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/xxx/.local/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip-oqesdw3p-build/setup.py", line 211, in build_extension
        self._install_from_source_package()
      File "/tmp/pip-oqesdw3p-build/setup.py", line 261, in _install_from_source_package
        raise Exception("Unable to find {}".format(url))
    Exception: Unable to find /home/xxx/lief-0.8.3-py3.4-linux.egg
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-oqesdw3p-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-t98kcwcm-record/install-record.txt --single-version-externally-managed --compile --user:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-3.4

creating build/lib.linux-x86_64-3.4/lief

copying lief/__init__.py -> build/lib.linux-x86_64-3.4/lief

running build_ext

Url: https://github.com/lief-project/packages/raw/lief-master-latest/lief-0.8.3-py3.4-linux.egg

HTTP Error 404: Not Found

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-oqesdw3p-build/setup.py", line 281, in <module>

    'sdist':     lief_sdist

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/xxx/.local/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run

    self.run_command('build')

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run

    self.run_command(cmd_name)

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/xxx/.local/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 75, in run

    _build_ext.run(self)

  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run

    self.build_extensions()

  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions

    self.build_extension(ext)

  File "/tmp/pip-oqesdw3p-build/setup.py", line 211, in build_extension

    self._install_from_source_package()

  File "/tmp/pip-oqesdw3p-build/setup.py", line 261, in _install_from_source_package

    raise Exception("Unable to find {}".format(url))

Exception: Unable to find /home/xxx/lief-0.8.3-py3.4-linux.egg

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-oqesdw3p-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-t98kcwcm-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-oqesdw3p-build
Storing debug log for failure in /home/xxx/.pip/pip.log

**Comment by romainthomas** [comment]
> Installing py packages should work by default in Cygwin.
 Looks like an python package installer problem.

In fact when installing LIEF Python package you are installing a **native** library.

> I tried now on Ubuntu and same error:

Yes you use **python 3.4** and there is no packages for python3.4 ...

Try:

``python3.5 -m pip install lief``

**Comment by kornos** [comment]
Thanks for your help , Thomas!
Can you guide me a lilttle bit further , cause still cant get it work.


kornos@ubuntu:~$ pip list |grep setuptools  < Python2
setuptools (18.4)
kornos@ubuntu:~$ pip3 list |grep setuptools
setuptools (36.6.0)
kornos@ubuntu:~$ python3.5 -m pip -V
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.5)
kornos@ubuntu:~$ python3.5m -m pip3 -V
/usr/bin/python3.5m: No module named pip3
kornos@ubuntu:~$ python3.5 -m pip install lief
Downloading/unpacking lief
  Downloading lief-0.8.3.post2.zip
  Running setup.py (path:/tmp/pip-build-b6nggyh7/lief/setup.py) egg_info for package lief
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-b6nggyh7/lief/setup.py", line 7, in <module>
        assert (LooseVersion(setuptools.__version__) >= LooseVersion(MIN_SETUPTOOLS_VERSION)), "LIEF requires a setuptools version '{}' or higher".format(MIN_SETUPTOOLS_VERSION)
    AssertionError: LIEF requires a setuptools version '31.0.0' or higher
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-b6nggyh7/lief/setup.py", line 7, in <module>

    assert (LooseVersion(setuptools.__version__) >= LooseVersion(MIN_SETUPTOOLS_VERSION)), "LIEF requires a setuptools version '{}' or higher".format(MIN_SETUPTOOLS_VERSION)

AssertionError: LIEF requires a setuptools version '31.0.0' or higher

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in

**Comment by romainthomas** [comment]
From the **README**: 

```bash
pip install setuptools --upgrade
```

**Comment by kornos** [comment]
ofc I did that already ;-) , but it doesnt work

pip is for Python2 , pip3 is for Python3
it seems max allowed version of setuptools for python 2 is:

ornos@ubuntu:~$ pip -V
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
kornos@ubuntu:~$ pip install setuptools --upgrade
Downloading/unpacking setuptools
  Downloading setuptools-36.6.0-py2.py3-none-any.whl (481kB): 481kB downloaded
Installing collected packages: setuptools
Successfully installed setuptools
Cleaning up...

kornos@ubuntu:~$ pip list |grep setuptools
setuptools (18.4)

^^Maximum version for python 2, I cannot update setuptools to ver 36

Update:
I managed to install lief on Pyton3.6/Windows.
But it seems that on Linux , when Python2 is also installed along Python3 , it still doesnt work.

**Comment by romainthomas** [comment]
``python3.5 -m pip install setuptools --upgrade``

**Comment by kornos** [comment]
I already did that earlier , THomas , as you can see in my posts below.

I can update setuptools to last ver (36) for python 3  , but not for python 2
it seems that if Python2 and Python3 are installed, 
when I try to install lief - python3 version , the installer checks out the setuptools version of python2.

**Comment by romainthomas** [comment]
I don't know how you manage your Python environments  

but:

```bash
$ mkvirtualenv --no-setuptools -p /usr/bin/python2.7 lief_python27
$ python --version                                                                                                                                                                                                   
Python 2.7.14
$ python2.7 -m pip install setuptools==31.0.0
python2.7 -m pip install setuptools==31.0.0                                                                                                                                                                        
Collecting setuptools==31.0.0
  Using cached setuptools-31.0.0-py2.py3-none-any.whl
Installing collected packages: setuptools
Successfully installed setuptools-31.0.0
$ python2.7 -c "import setuptools;print(setuptools.__version__)"
31.0.0
$ python2.7 -m pip install lief 
Collecting lief
Installing collected packages: lief
Successfully installed lief-0.8.3
```

**Comment by kornos** [comment]
Maybe it's a Ubuntu or python installing system bug on my part.
Weird part is I cannot update setuptools more than 18.4 on windows too

kornos@ubuntu:~$  python2.7 -m pip install setuptools==31.0.0
Downloading/unpacking setuptools==31.0.0
  Downloading setuptools-31.0.0-py2.py3-none-any.whl (477kB): 477kB downloaded
Installing collected packages: setuptools
Successfully installed setuptools
Cleaning up...
kornos@ubuntu:~$ pip list |grep setuptools
setuptools (18.4)
kornos@ubuntu:~$  python2.7 -c "import setuptools;print(setuptools.__version__)"
18.4

Ok , thanks v much , I will not buzz on this problem anymore.
Looks like a Ubuntu or Python bug.
I will upgrade to last Ubuntu and see if the problem still manifest itself.

Thanks v much

**Comment by frennkie** [comment]
I have the same problem on Ubuntu 14.04 on Python3.4 with a virtual environment. Here is what I'm doing (doing the same thing on Ubuntu 16.04 works fine):

```
virtualenv -p python3 --no-site-packages /tmp/venv
cd /tmp/venv
source /tmp/venv/bin/activate
pip3 install -U pip setuptools
pip3 list

```
Output:

```
[...]
(venv) user@ubuntu144:/tmp/venv$ pip3 install -U pip setuptools
Requirement already up-to-date: pip in ./lib/python3.4/site-packages
Requirement already up-to-date: setuptools in ./lib/python3.4/site-packages
(venv) user@ubuntu144:/tmp/venv$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip (9.0.1)
setuptools (38.4.1)
wheel (0.30.0)
```

Then I run `pip3 install lief`

```
(venv) user@ubuntu144:/tmp/venv$ pip3 install lief
Collecting lief
  Downloading lief-0.8.3.post3.zip
Building wheels for collected packages: lief
  Running setup.py bdist_wheel for lief ... error
  Complete output from command /tmp/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2dxvhd5w/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /
tmp/tmp1zr0tpzvpip-wheel- --python-tag cp34:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.4
  creating build/lib.linux-x86_64-3.4/lief
  copying lief/__init__.py -> build/lib.linux-x86_64-3.4/lief
  running build_ext
  Url: https://github.com/lief-project/LIEF/releases/download/0.8.3/lief-0.8.3-py3.4-linux.egg
  HTTP Error 404: Not Found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-2dxvhd5w/lief/setup.py", line 281, in <module>
      'sdist':     lief_sdist
    File "/tmp/venv/lib/python3.4/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/venv/lib/python3.4/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/venv/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 75, in run
      _build_ext.run(self)
    File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions
      self.build_extension(ext)
    File "/tmp/pip-build-2dxvhd5w/lief/setup.py", line 211, in build_extension
      self._install_from_source_package()
    File "/tmp/pip-build-2dxvhd5w/lief/setup.py", line 261, in _install_from_source_package
      raise Exception("Unable to find {}".format(url))
  Exception: Unable to find /home/user/lief-0.8.3-py3.4-linux.egg

  ----------------------------------------
  Failed building wheel for lief
  Running setup.py clean for lief
Failed to build lief
Installing collected packages: lief
  Running setup.py install for lief ... error
    Complete output from command /tmp/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2dxvhd5w/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-uaek0cl3-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/venv/include/site/python3.4/lief:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    creating build/lib.linux-x86_64-3.4/lief
    copying lief/__init__.py -> build/lib.linux-x86_64-3.4/lief
    running build_ext
    Url: https://github.com/lief-project/LIEF/releases/download/0.8.3/lief-0.8.3-py3.4-linux.egg
    HTTP Error 404: Not Found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2dxvhd5w/lief/setup.py", line 281, in <module>
        'sdist':     lief_sdist
      File "/tmp/venv/lib/python3.4/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/venv/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/venv/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip-build-2dxvhd5w/lief/setup.py", line 211, in build_extension
        self._install_from_source_package()
      File "/tmp/pip-build-2dxvhd5w/lief/setup.py", line 261, in _install_from_source_package
        raise Exception("Unable to find {}".format(url))
    Exception: Unable to find /home/user/lief-0.8.3-py3.4-linux.egg

    ----------------------------------------
Command "/tmp/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2dxvhd5w/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-uaek0cl3-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/venv/include/site/python3.4/lief" failed with error code 1 in /tmp/pip-build-2dxvhd5w/lief/
```

Unfortunately I have an application running on a Ubuntu 14.04 host that has a dependency for lief... :-/

**Comment by frennkie** [comment]
I just noticed you "pre-package" (?!) for Py2.7, Py3.5 and Py3.6. So that explains why the URL https://github.com/lief-project/LIEF/releases/download/0.8.3/lief-0.8.3-py3.4-linux.egg gives a 404.

**Comment by romainthomas** [comment]
Hi, Actually LIEF python packages are only built for Python ``2.7``, ``3.5`` and ``3.6``. 
It's a trade off between CI speed and packages available.

If you really need LIEF for Python 3.4 to can compiled it yourself as explained in the doc: 
https://lief.quarkslab.com/doc/compilation.html#library-and-python-bindings

**Comment by frennkie** [comment]
I completely understand. I'm also fine with using never software (e.g. `Py3.5`). But I'm contributing to a project (https://github.com/viper-framework/viper/) which uses PyMISP (https://github.com/MISP/PyMISP) which uses LIEF. 

Due to this chain any Viper users that are using (a plattform with) `Py3.4` will have to migrate now.

Don't get me wrong.. I think open source and being able to built upon software that other people are creating (in their free time) is great. So I'm not *blaming* you in any way.. just asking whether you could reconsider and add `Py3.4` to your build pipeline... at least for maybe a year..?! :-)

**Comment by romainthomas** [comment]
What I could do is to provide Python 3.4 package for LIEF **releases** (i.e. tagged commit)

**Comment by frennkie** [comment]
Yes.. I think that would be all that I need.. I want to run `pip3 install lief` on `Py34` to install a latest **release**.

**Comment by ostefano** [comment]
+1 for `Py34` package for **releases** if possible.
