### ISSUE TITLE
Cannot install older Lief versions

### ISSUE THREAD

**Issue by rammy22** [lief-project/LIEF#117]
I have a project that works on lief==0.8.1
It looks like the libs are missing:
```
Url: https://github.com/lief-project/packages/raw/lief-master-latest/lief-0.8.1-py2.7-osx.egg
    HTTP Error 404: Not Found
```

Can you fix please?

**Comment by romainthomas** [comment]
I suggest you to upgrade to ``0.8.3`` (no API changes)
Packages for the ``0.8.1`` are still available here:

* https://pypi.python.org/pypi/lief/0.8.1
* https://github.com/lief-project/LIEF/releases/tag/0.8.1

**Comment by rammy22** [comment]
my point is that the pip install process is broken, when installing a version specific package, eg
`pip install lief==0.8.1`. This affects the continuous integration process :(

**Comment by romainthomas** [comment]
I don't how you setup your CI but:

```bash
$ mkvirtualenv lief_issue
$ pip install lief==0.8.1
Collecting lief==0.8.1
  Using cached lief-0.8.1.zip
Building wheels for collected packages: lief
  Running setup.py bdist_wheel for lief ... done
Successfully built lief
Installing collected packages: lief
Successfully installed lief-0.8.1
$ python
>>> import lief
>>> lief.__version__
'0.8.1-f4e2ae0'
```

**Comment by rammy22** [comment]
``` python
pip install lief==0.8.1
The directory '/Users/test/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/test/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting lief==0.8.1
  Downloading lief-0.8.1.zip
Installing collected packages: lief
  Running setup.py install for lief ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-nVu8vc/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tgtClo-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.13-intel-2.7
    creating build/lib.macosx-10.13-intel-2.7/lief
    copying lief/__init__.py -> build/lib.macosx-10.13-intel-2.7/lief
    running build_ext
    Url: https://github.com/lief-project/packages/raw/lief-master-latest/lief-0.8.1-py2.7-osx.egg
    HTTP Error 404: Not Found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-nVu8vc/lief/setup.py", line 281, in <module>
        'sdist':     lief_sdist
      File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Python/2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Python/2.7/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/Library/Python/2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
        _build_ext.build_ext.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/Library/Python/2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
        self.build_extension(ext)
      File "/private/tmp/pip-build-nVu8vc/lief/setup.py", line 211, in build_extension
        self._install_from_source_package()
      File "/private/tmp/pip-build-nVu8vc/lief/setup.py", line 261, in _install_from_source_package
        raise Exception("Unable to find {}".format(url))
    Exception: Unable to find /Users/test/lief-0.8.1-py2.7-osx.egg
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-nVu8vc/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tgtClo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-nVu8vc/lief/
```

**Comment by romainthomas** [comment]
Do you have the same error for the ``0.8.3`` ?

**Comment by rammy22** [comment]
no, just for 8.1

**Comment by romainthomas** [comment]
OK I confirm the error

**Comment by romainthomas** [comment]
`pip install lief==0.8.1.post1` should work

**Comment by rammy22** [comment]
Hi @romainthomas ,

I'm running into the same issue again. I've use lief 0.8.3 for some weeks now and build a python project on top of it. Today, when deploying and testing this package in a virtual environment I get errors when installing lief==0.8.3 as it does not exist anymore, instead 0.8.3.post3 is the only versions available, which causes my unittests to fail.
This deployment strategy for python packaged makes it impossible for me to use lief as I cannot rely that a version will exist tomorrow. Can you at least not delete older versions? I cannot find the 0.8.3 (no post afaik) anywhere.

Thank you!

**Comment by romainthomas** [comment]
Yes it's not very convenient and next releases shouldn't suffer of this problem. 
As a workaround you can use:
```bash
lief==0.8.3.post3
# or
lief<0.8.4
```

**Comment by rammy22** [comment]
Thanks, that's what I've been using, but there are a few issues with this: 

- the ParserConfig is missing in this post
- the default ParserConfig is/was different between the MachO.parse() flavours. For example in parse(filename) it was using deep and in parse(raw) it was using quick.

The original 0.8.3 version i was using for the project is not available anymore so I need to , temporarily, install de dev version...

**Comment by romainthomas** [comment]
See #123 ...
