### ISSUE TITLE
AttributeError: '_pylief.MachO.Binary' object has no attribute 'add'

### ISSUE THREAD

**Issue by deathmemory** [lief-project/LIEF#190]
it said these error , when i use `tests/elf/test.py` code

```python
ls   = lief.parse("/bin/ls")
stub = lief.parse("./hook.so")

ls.add(stub.segments[0])
```

error info:

```python
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/dmemory/PycharmProjects/liefTest/liefTest.py", line 23, in <module>
    segment                 = ls.add(segment)
AttributeError: '_pylief.MachO.Binary' object has no attribute 'add'
```

my OS is MacOSX

**Comment by romainthomas** [comment]
Yes it your case, "/bin/ls" is a Mach-O file not an ELF. So adding a **lief.ELF.Segment** fails...
