### ISSUE TITLE
GLIBCXX_3.4.20 not found when import lief Python 3.6.3 on RHEL 7.5

### ISSUE THREAD

**Issue by jezkerwin** [lief-project/LIEF#207]
Hello,
I've compiled and installed the most recent version of LIEF on RHEL 7.5.
When I run Python 3.6 from the Software Collections SCL (scl enable rh-python36 bash) I get the following error.
LIEF was compiled using the devtoolset-7 software collection.

```
Python 3.6.3 (default, Jan  9 2018, 10:19:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/lief-0.9.0-py3.6-linux-x86_64.egg/lief/__init__.py", line 4, in <module>
    import _pylief
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/lief-0.9.0-py3.6-linux-x86_64.egg/_pylief.cpython-36m-x86_64-linux-gnu.so)
>>>
```

I've been unable to figure out how to resolve the issue and was wondering if someone else has come across it.

Can I specify to GLIBCXX_3.4.19 which my system does have at compile time, ie. using a switch?

**Comment by jezkerwin** [comment]
I figured out the issue.
I following the steps in this docker file for centos and it worked on RHEL

https://github.com/lief-project/Dockerlief/blob/master/dockerlief/dockerfiles/centos.docker
