### ISSUE TITLE
Can't install LIEF on Python 3.7

### ISSUE THREAD

**Issue by yammesicka** [lief-project/LIEF#231]
### TL;DR:
There is no `lief-0.9.0-py3.7-linux.egg` file in https://github.com/lief-project/packages/raw/lief-master-latest/ (nor in https://github.com/lief-project/packages/tree/lief-master-latest)

### Logs

```bash
[yam@yam ~]$ python --version
Python 3.7.1
[yam@yam ~]$ uname -a
Linux yam 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
```

```bash
[yam@yam ~]$ pip install --user --upgrade setuptools
Requirement already up-to-date: setuptools in /usr/lib/python3.7/site-packages (40.5.0)
```

```bash
[yam@yam ~]$ pip install -U --user lief
Collecting lief
  Using cached https://files.pythonhosted.org/packages/cd/0e/0d6f3357975dd1530aeb4b4a84a99d493775391758378fb5109f47b613f9/lief-0.9.0.zip
Installing collected packages: lief
  Running setup.py install for lief ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rzenurz9/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wfucwvlu/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/lief
    copying lief/__init__.py -> build/lib.linux-x86_64-3.7/lief
    running build_ext
    Url: https://github.com/lief-project/LIEF/releases/download/0.9.0/lief-0.9.0-py3.7-linux.egg
    HTTP Error 404: Not Found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rzenurz9/lief/setup.py", line 285, in <module>
        'sdist':     lief_sdist
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-rzenurz9/lief/setup.py", line 215, in build_extension
        self._install_from_source_package()
      File "/tmp/pip-install-rzenurz9/lief/setup.py", line 265, in _install_from_source_package
        raise Exception("Unable to find {}".format(url))
    Exception: Unable to find /home/yam/lief-0.9.0-py3.7-linux.egg
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rzenurz9/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wfucwvlu/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-rzenurz9/lief/
```

```bash
[yam@yam ~]$ pip install --user --upgrade https://github.com/lief-project/packages/tree/lief-master-latest/pylief-0.9.0.dev.zip
Collecting https://github.com/lief-project/packages/tree/lief-master-latest/pylief-0.9.0.dev.zip
  Downloading https://github.com/lief-project/packages/tree/lief-master-latest/pylief-0.9.0.dev.zip
     - 51kB 354kB/s
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 836, in unpack_url
    progress_bar=progress_bar
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 677, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 578, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 463, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

```bash
yam@yam ~]$ pip install https://github.com/lief-project/packages/blob/lief-master-latest/pylief-0.9.0.dev.zip?raw=true
Collecting https://github.com/lief-project/packages/blob/lief-master-latest/pylief-0.9.0.dev.zip?raw=true
  Using cached https://github.com/lief-project/packages/blob/lief-master-latest/pylief-0.9.0.dev.zip?raw=true
Installing collected packages: lief
  Running setup.py install for lief ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-2c7udo6j/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5get4fck/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/lief
    copying lief/__init__.py -> build/lib.linux-x86_64-3.7/lief
    running build_ext
    Url: https://github.com/lief-project/packages/raw/lief-master-latest/lief-0.9.0-py3.7-linux.egg
    HTTP Error 404: Not Found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-2c7udo6j/setup.py", line 279, in <module>
        'sdist':     lief_sdist
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-req-build-2c7udo6j/setup.py", line 213, in build_extension
        self._install_from_source_package()
      File "/tmp/pip-req-build-2c7udo6j/setup.py", line 263, in _install_from_source_package
        raise Exception("Unable to find {}".format(url))
    Exception: Unable to find /home/yam/lief-0.9.0-py3.7-linux.egg
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-2c7udo6j/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5get4fck/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-2c7udo6j/
```

**Comment by romainthomas** [comment]
Hello, Yes current configuration of CI (Travis and Appveyor) doesn't include Python 3.7. I'll setup them during the month.
If you can't wait, you can compile LIEF for python 3.7 as follow:

```bash
$ cmake -DPYTHON_VERSION=3.7 .. && make pyLIEF
```

**Comment by tincho9** [comment]
@romainthomas Can you further document the build process for python 3.7 please?

**Comment by romainthomas** [comment]
Just finished to setup CI for Python 3.7.  It's currently only available in *master* packages:
```bash
$ pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.9.0.dev.zip
```
