### ISSUE TITLE
Crash on wsl when rebuilding a simple ARM ELF to Intel (and vice versa)

### ISSUE THREAD

**Issue by shiftre** [lief-project/LIEF#232]
Root caused to this snippet:

```
def modify_elf_arch(fname):
    bin = lief.parse(fname)
    bin.header.machine_type = lief.ELF.ARCH.ARM
    return bin.write(fname)
```

```
(gdb) x/10i $pc
=> 0x7ffffdae5c9e <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1230>:  mov    (%rdx,%rax,8),%rax
   0x7ffffdae5ca2 <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1234>:  mov    %rax,%rdi
   0x7ffffdae5ca5 <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1237>:  mov    %rax,0x38(%rsp)
   0x7ffffdae5caa <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1242>:  mov    (%rax),%rax
   0x7ffffdae5cad <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1245>:  callq  *0x58(%rax)
   0x7ffffdae5cb0 <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1248>:  mov    0x18(%rsp),%rax
   0x7ffffdae5cb5 <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1253>:  mov    0x30(%rax),%rax
   0x7ffffdae5cb9 <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1257>:  mov    0x88(%rax),%rdx
   0x7ffffdae5cc0 <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1264>:  mov    0x90(%rax),%rax
   0x7ffffdae5cc7 <_ZN4LIEF3ELF7Builder14build_sectionsINS0_5ELF32EEEvv+1271>:  sub    %rdx,%rax
(gdb) bt
#0  0x00007ffffdae5c9e in void LIEF::ELF::Builder::build_sections<LIEF::ELF::ELF32>() () from /usr/local/lib/python2.7/dist-packages/_pylief.so
#1  0x00007ffffdaf12a6 in void LIEF::ELF::Builder::build<LIEF::ELF::ELF32>() () from /usr/local/lib/python2.7/dist-packages/_pylief.so
#2  0x00007ffffdaa29ef in LIEF::ELF::Binary::write(std::string const&) () from /usr/local/lib/python2.7/dist-packages/_pylief.so
#3  0x00007ffffd6dc959 in void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, LIEF::ELF::Binary, std::string const&, pybind11::name, pybind11::is_method, pybind11::sibling, char [42], pybind11::arg, pybind11:
:return_value_policy>(void (LIEF::ELF::Binary::*)(std::string const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [42], pybind11::arg const&, pybind11::return_value_policy const&)::{lambda
(LIEF::ELF::Binary*, std::string const&)#1}, void, LIEF::ELF::Binary*, std::string const&, pybind11::name, pybind11::is_method, pybind11::sibling, char [42], pybind11::arg, pybind11::return_value_policy>(pybind11::cpp_function::initializ
e<void, LIEF::ELF::Binary, std::string const&, pybind11::name, pybind11::is_method, pybind11::sibling, char [42], pybind11::arg, pybind11::return_value_policy>(void (LIEF::ELF::Binary::*)(std::string const&), pybind11::name const&, pybin
d11::is_method const&, pybind11::sibling const&, char const (&) [42], pybind11::arg const&, pybind11::return_value_policy const&)::{lambda(LIEF::ELF::Binary*, std::string const&)#1}&&, void (*)(LIEF::ELF::Binary*, std::string const&), py
bind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [42], pybind11::arg const&, pybind11::return_value_policy const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_ca
ll) () from /usr/local/lib/python2.7/dist-packages/_pylief.so
#4  0x00007ffffd626ad7 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /usr/local/lib/python2.7/dist-packages/_pylief.so
#5  0x00000000004c37ed in PyEval_EvalFrameEx ()
#6  0x00000000004c136f in PyEval_EvalFrameEx ()
#7  0x00000000004b9ab6 in PyEval_EvalCodeEx ()
#8  0x00000000004eb30f in ?? ()
#9  0x00000000004e5422 in PyRun_FileExFlags ()
#10 0x00000000004e3cd6 in PyRun_SimpleFileExFlags ()
#11 0x0000000000493ae2 in Py_Main ()
#12 0x00007ffffee30830 in __libc_start_main (main=0x4934c0 <main>, argc=2, argv=0x7ffffffedf18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffffffedf08) at ../csu/libc-start.c:291
#13 0x00000000004933e9 in _start ()

(gdb) i r
rax            0x0      0
rbx            0x7ffffffed620   140737488279072
rcx            0x7fffff1d4b20   140737473497888
rdx            0x0      0
rsi            0x7ffffffed450   140737488278608
rdi            0x9d3590 10302864
rbp            0x7ffffffed580   0x7ffffffed580
rsp            0x7ffffffed3b0   0x7ffffffed3b0
r8             0xe5bdb0 15056304
r9             0x0      0
r10            0x22     34
r11            0x22     34
r12            0x0      0
r13            0x7ffffe1e2a50   140737456777808
r14            0x7fffff5e8d40   140737477774656
r15            0x0      0
rip            0x7ffffdae5c9e   0x7ffffdae5c9e <void LIEF::ELF::Builder::build_sections<LIEF::ELF::ELF32>()+1230>
eflags         0x10246  [ PF ZF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      
```

Running on WSL, Python 2.7 and Python 3.5.2

**Comment by romainthomas** [comment]
Indeed moving from an ELF32 to and ELF64 (or vice versa) is not supported.

**Comment by shiftre** [comment]
I was only trying to modify the architecture from ARM to i386 and it crashed, not moving from different bitness : / 

Any hints?

**Comment by romainthomas** [comment]
Could you try on a non WSL. I tried on Linux with success. Also can you past the version of LIEF ?
