### ISSUE TITLE
lief-0.9.0-py2.7-linux_x32.egg HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by blshkv** [lief-project/LIEF#248]
https://paste.pound-python.org/show/EPq4Z4BP1M4ebyGl0PPT/
```
 
 * Package:    dev-python/lief-0.9.0-r1
 * Repository: pentoo
 * Maintainer: blshkv@pentoo.org
 * USE:        abi_x86_32 elibc_glibc kernel_linux python_targets_python2_7 python_targets_python3_6 userland_GNU x86
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking lief-0.9.0.zip to /var/tmp/portage/dev-python/lief-0.9.0-r1/work
>>> Unpacking lief-0.9.0-py2.7-linux.egg to /var/tmp/portage/dev-python/lief-0.9.0-r1/work
unpack lief-0.9.0-py2.7-linux.egg: file format not recognized. Ignoring.
>>> Unpacking lief-0.9.0-py3.6-linux.egg to /var/tmp/portage/dev-python/lief-0.9.0-r1/work
unpack lief-0.9.0-py3.6-linux.egg: file format not recognized. Ignoring.
>>> Source unpacked in /var/tmp/portage/dev-python/lief-0.9.0-r1/work
>>> Preparing source in /var/tmp/portage/dev-python/lief-0.9.0-r1/work/lief-0.9.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/lief-0.9.0-r1/work/lief-0.9.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/lief-0.9.0-r1/work/lief-0.9.0 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
python2.7 setup.py build
running build
running build_py
creating /var/tmp/portage/dev-python/lief-0.9.0-r1/work/lief-0.9.0-python2_7/lib/lief
copying lief/__init__.py -> /var/tmp/portage/dev-python/lief-0.9.0-r1/work/lief-0.9.0-python2_7/lib/lief
warning: build_py: byte-compiling is disabled, skipping.

running build_ext
Url: https://github.com/lief-project/LIEF/releases/download/0.9.0/lief-0.9.0-py2.7-linux_x32.egg
HTTP Error 404: Not Found
Traceback (most recent call last):
  File "setup.py", line 285, in <module>
```

**Comment by spiiin** [comment]
I am also got a similar error while trying to install lief via pip for android pydroid3:
```
>pip install lief
Collecting lief
  Using cached https://files.pythonhosted.org/packages/cd/0e/0d6f3357975dd1530aeb4b4a84a99d493775391758378fb5109f47b613f9/lief-0.9.0.zip
Installing collected packages: lief
  Running setup.py install for lief ... error
    Complete output from command /data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/data/data/ru.iiec.pydroid3/cache/pip-install-_gmxnprk/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/ru.iiec.pydroid3/cache/pip-record-yuo7a43k/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.6
    creating build/lib.linux-armv7l-3.6/lief
    copying lief/__init__.py -> build/lib.linux-armv7l-3.6/lief
    running build_ext
    Url: https://github.com/lief-project/LIEF/releases/download/0.9.0/lief-0.9.0-py3.6-linux_x32.egg
    HTTP Error 404: Not Found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/ru.iiec.pydroid3/cache/pip-install-_gmxnprk/lief/setup.py", line 285, in <module>
        'sdist':     lief_sdist
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/core.py", line 196, in setup
        dist.run_commands()
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "/data/data/ru.iiec.pydroid3/cache/pip-install-_gmxnprk/lief/setup.py", line 215, in build_extension
        self._install_from_source_package()
      File "/data/data/ru.iiec.pydroid3/cache/pip-install-_gmxnprk/lief/setup.py", line 265, in _install_from_source_package
        raise Exception("Unable to find {}".format(url))
    Exception: Unable to find /data/user/0/ru.iiec.pydroid3/app_HOME/lief-0.9.0-py3.6-linux_x32.egg
    
    ----------------------------------------
Command "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/data/data/ru.iiec.pydroid3/cache/pip-install-_gmxnprk/lief/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/ru.iiec.pydroid3/cache/pip-record-yuo7a43k/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/ru.iiec.pydroid3/cache/pip-install-_gmxnprk/lief/
```

I see the android build of libLIEF.so, so looks like lief can be built for armeabi-v7a architecture. It will be cool if it can be used directly from android python. Basically, it needs something like lief-0.9.0-py3.6-linux_armeabi.egg file =)

Currently, I tried to install lief-0.9.0-py3.6-linux.egg via easy_setup, and replace file _pylief.cpython-36m-x86_64-linux-gnu.so with libLIEF.so from LIEF-0.9.0-Android-armeabi-v7a.tar.gz, but it is not working because android file has no init python functions (PyInit__pylief). I hope, lief will support android-python in future.

**Comment by romainthomas** [comment]
CI provides pre-built packges for the following platforms:

* Linux: x86_64 - Python 3.5, 3.6, 3.6
* OSX: x86_64 - Python 3.5, 3.6, 3.6
* Windows: x86_64 - x86 - Python 3.5, 3.6, 3.6

It doesn't include Linux **x86** but you can compile the library using "-DLIEF_FORCE32=on"
A [dockerfile](https://github.com/lief-project/Dockerlief/blob/master/dockerlief/dockerfiles/android.docker) is provided to compile LIEF for Android platform
