### ISSUE TITLE
Cannot install lief at macOS Mojave

### ISSUE THREAD

**Issue by dukebarman** [lief-project/LIEF#342]
**Describe the bug**
```
$ pip3 install lief
Collecting lief
  Using cached https://files.pythonhosted.org/packages/cd/0e/0d6f3357975dd1530aeb4b4a84a99d493775391758378fb5109f47b613f9/lief-0.9.0.zip
Building wheels for collected packages: lief
  Building wheel for lief (setup.py) ... error
  ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-wheel-_z7wqt0x --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/lief
  copying lief/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/lief
  running build_ext
  Url: https://github.com/lief-project/LIEF/releases/download/0.9.0/lief-0.9.0-py3.7-osx.egg
  HTTP Error 404: Not Found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/setup.py", line 285, in <module>
      'sdist':     lief_sdist
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/setup.py", line 215, in build_extension
      self._install_from_source_package()
    File "/private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/setup.py", line 265, in _install_from_source_package
      raise Exception("Unable to find {}".format(url))
  Exception: Unable to find /Users/dukebarman/lief-0.9.0-py3.7-osx.egg
  ----------------------------------------
  ERROR: Failed building wheel for lief
  Running setup.py clean for lief
Failed to build lief
Installing collected packages: lief
  Running setup.py install for lief ... error
    ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-record-lohj7mtb/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/lief
    copying lief/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/lief
    running build_ext
    Url: https://github.com/lief-project/LIEF/releases/download/0.9.0/lief-0.9.0-py3.7-osx.egg
    HTTP Error 404: Not Found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/setup.py", line 285, in <module>
        'sdist':     lief_sdist
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/setup.py", line 215, in build_extension
        self._install_from_source_package()
      File "/private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/setup.py", line 265, in _install_from_source_package
        raise Exception("Unable to find {}".format(url))
    Exception: Unable to find /Users/dukebarman/lief-0.9.0-py3.7-osx.egg
    ----------------------------------------
ERROR: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-record-lohj7mtb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_t/f186x6qx787c9cf4h8_5487w0000gn/T/pip-install-e6o8t8ci/lief/
```

**To Reproduce**
`pip3 install lief`

**Expected behavior**
Successfully installed lief.

**Environment (please complete the following information):**
 - macOS Mojave 10.14.6

**Comment by romainthomas** [comment]
You can try: 
```
pip install [--user] lief==0.10.0.dev0
```
or 
```
pip install [--user] --index-url  https://lief-project.github.io/packages lief
```
For the nightly build

**Comment by dukebarman** [comment]
Thanks! It works.
