### ISSUE TITLE
CMake Error at CMakeLists.txt:541 (add_subdirectory) for package folder

### ISSUE THREAD

**Issue by mobeigi** [lief-project/LIEF#373]
**Describe the bug**
Unable to install with CMAKE issue.

Output:
```
PS C:\lief> py -3 -m pip install file:///c:/lief
Processing c:\lief
Installing collected packages: lief
  Found existing installation: lief 0.10.1
    Can't uninstall 'lief'. No files were found to uninstall.
    Running setup.py install for lief ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mo\\AppData\\Local\\Temp\\pip-req-build-2qjwzztu\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mo\\AppData\\Local\\Temp\\pip-req-build-2qjwzztu\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mo\AppData\Local\Temp\pip-record-fgzvzx5l\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Mo\AppData\Local\Temp\pip-req-build-2qjwzztu\
    Complete output (89 lines):
    0.10.1
    running install
    running build
    running build_ext
    cmake C:\Users\Mo\AppData\Local\Temp\pip-req-build-2qjwzztu -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Mo\AppData\Local\Temp\pip-req-build-2qjwzztu\build\temp.win-amd64-3.8 -DPYTHON_EXECUTABLE=C:\Python38\python.exe -DLIEF_PYTHON_API=on -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Mo\AppData\Local\Temp\pip-req-build-2qjwzztu\build\temp.win-amd64-3.8 -DLIEF_USE_CRT_RELEASE=MT -A x64
    -- Building for: Visual Studio 16 2019
    -- LIEF_CRT: /MT
    -- Using Release VC++ CRT: MT
    -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
    -- The C compiler identification is MSVC 19.24.28314.0
    -- The CXX compiler identification is MSVC 19.24.28314.0
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- LIEF 0.10.0
    -- ccache: ON
    -- Enable JSON support
    -- Enable Frozen (C++14 support)
    -- Number of parallel compiler jobs set to /MP
    -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
    -- Configuration Types: Debug;Release;MinSizeRel;RelWithDebInfo
    -- Build Types: Release
    -- Found PythonInterp: C:/Python38/python.exe (found suitable version "3.8", minimum required is "3.5")
    -- Found PythonLibs: C:/Python38/libs/Python38.lib
    -- Python version: 3.5
    -- Python lib:     C:/Python38/libs/Python38.lib
    -- Python include: C:/Python38/include
    -- Python interpreter: C:/Python38/python.exe
    -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED
    -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED - Failed
    -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED
    -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED - Failed
    -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS
    -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Failed
    -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS
    -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Failed
    -- Performing Test HAS_ANSI
    -- Performing Test HAS_ANSI - Failed
    CMake Error at CMakeLists.txt:541 (add_subdirectory):
      add_subdirectory given source
      "C:/Users/Mo/AppData/Local/Temp/pip-req-build-2qjwzztu/package" which is
      not an existing directory.


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Mo/AppData/Local/Temp/pip-req-build-2qjwzztu/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/Mo/AppData/Local/Temp/pip-req-build-2qjwzztu/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Mo\AppData\Local\Temp\pip-req-build-2qjwzztu\setup.py", line 363, in <module>
        setup(
      File "C:\Python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Python38\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python38\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Python38\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Mo\AppData\Local\Temp\pip-req-build-2qjwzztu\setup.py", line 78, in run
        self.build_extension(ext)
      File "C:\Users\Mo\AppData\Local\Temp\pip-req-build-2qjwzztu\setup.py", line 202, in build_extension
        subprocess.check_call(configure_cmd, cwd=self.build_temp, env=env)
      File "C:\Python38\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Mo\\AppData\\Local\\Temp\\pip-req-build-2qjwzztu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Mo\\AppData\\Local\\Temp\\pip-req-build-2qjwzztu\\build\\temp.win-amd64-3.8', '-DPYTHON_EXECUTABLE=C:\\Python38\\python.exe', '-DLIEF_PYTHON_API=on', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Mo\\AppData\\Local\\Temp\\pip-req-build-2qjwzztu\\build\\temp.win-amd64-3.8', '-DLIEF_USE_CRT_RELEASE=MT', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
  ERROR: Can't roll back lief; was not uninstalled
ERROR: Command errored out with exit status 1: 'C:\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mo\\AppData\\Local\\Temp\\pip-req-build-2qjwzztu\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mo\\AppData\\Local\\Temp\\pip-req-build-2qjwzztu\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mo\AppData\Local\Temp\pip-record-fgzvzx5l\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

**Environment (please complete the following information):**
 - System and Version : Windows 10 (18362.535)
 - Target format (PE, ELF, Mach-O): N/A
 - LIEF commit version: Attempting to install 0.10.1

**Comment by mobeigi** [comment]
I was able to install from a local directory using master because it contains the `package` folder while the `lief-0.10.1.tar.gz` served from pip did not have. Unfortunately this presents an error of its own when trying to import the library which may be unrelated:
```
Fatal Python error: _PyInterpreterState_Get(): no current thread state
Python runtime state: initialized

Current thread 0x00000808 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1101 in create_module
  File "<frozen importlib._bootstrap>", line 556 in module_from_spec
  File "<frozen importlib._bootstrap>", line 657 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "C:\Users\Mo\Desktop\Day24\Online\test.py", line 1 in <module>
```

**Comment by romainthomas** [comment]
Yep, it seems there is an issue with Python 3.8 on Windows. I close this issue as it's not related to LIEF.

**Comment by romainthomas** [comment]
Sorry @mobeigi I mess your first issue. 0b205665c3d86fb1a01f149afcdfe8ec8e5a0724 fixes your issue.

**Comment by mobeigi** [comment]
@romainthomas Able to install from master now!

Any idea about the Python 3.8 issue on Windows? Any solution besides downgrading py version?

**Comment by romainthomas** [comment]
I did not investigated the issue a lot but Python 3.8 works well on OSX and Linux

**Comment by farzonl** [comment]
I'm seeing this issue pop up with python 3.9 on OS X 10.12.6 what is a good version to downgrade to?
