### ISSUE TITLE
Building LIEF wheel on pypy venv failed with a CMake error

### ISSUE THREAD

**Issue by Wenzel** [lief-project/LIEF#471]
**Describe the bug**
Installing lief package in a virtualenv for pypy leads to a CMake error

**To Reproduce**
~~~
virtualenv -p pypy3 venv
source venv/bin/activate
pip install lief
~~~

**Expected behavior**
Lief should have been installed

**What happened**
~~~
  Running setup.py clean for lief
Failed to build lief
Installing collected packages: lief
    Running setup.py install for lief ... error
    ERROR: Command errored out with exit status 1:
     command: /home/wenzel/Projets/checksec.py/venv-pypy/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nl285u7n/lief/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nl285u7n/lief/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5nz6ls9h/install-record.txt --single-version-externally-managed --compile --install-headers /home/wenzel/Projets/checksec.py/venv-pypy/include/site/python3.6/lief
         cwd: /tmp/pip-install-nl285u7n/lief/
    Complete output (129 lines):
    0.10.1
    running install
    running build
    running build_ext
    1.10.0
    cmake /tmp/pip-install-nl285u7n/lief -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-nl285u7n/lief/build -DPYTHON_EXECUTABLE=/home/wenzel/Projets/checksec.py/venv-pypy/bin/pypy3 -DLIEF_PYTHON_API=on -DCMAKE_BUILD_TYPE=Release
    -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- LIEF 0.10.0
    -- ccache: ON
    -- Enable JSON support
    -- Enable Frozen (C++14 support)
    -- Performing Test C_SUPPORTS_WALL
    -- Performing Test C_SUPPORTS_WALL - Success
    -- Performing Test CXX_SUPPORTS_WALL
    -- Performing Test CXX_SUPPORTS_WALL - Success
    -- Performing Test C_SUPPORTS_WEXTRA
    -- Performing Test C_SUPPORTS_WEXTRA - Success
    -- Performing Test CXX_SUPPORTS_WEXTRA
    -- Performing Test CXX_SUPPORTS_WEXTRA - Success
    -- Performing Test C_SUPPORTS_WPEDANTIC
    -- Performing Test C_SUPPORTS_WPEDANTIC - Success
    -- Performing Test CXX_SUPPORTS_WPEDANTIC
    -- Performing Test CXX_SUPPORTS_WPEDANTIC - Success
    -- Performing Test C_SUPPORTS_NO_STACK_PROTECTOR
    -- Performing Test C_SUPPORTS_NO_STACK_PROTECTOR - Success
    -- Performing Test CXX_SUPPORTS_NO_STACK_PROTECTOR
    -- Performing Test CXX_SUPPORTS_NO_STACK_PROTECTOR - Success
    -- Performing Test C_SUPPORTS_OMIT_FRAME_POINTER
    -- Performing Test C_SUPPORTS_OMIT_FRAME_POINTER - Success
    -- Performing Test CXX_SUPPORTS_OMIT_FRAME_POINTER
    -- Performing Test CXX_SUPPORTS_OMIT_FRAME_POINTER - Success
    -- Performing Test C_SUPPORTS_NO_STRICT_ALIASING
    -- Performing Test C_SUPPORTS_NO_STRICT_ALIASING - Success
    -- Performing Test CXX_SUPPORTS_NO_STRICT_ALIASING
    -- Performing Test CXX_SUPPORTS_NO_STRICT_ALIASING - Success
    -- Performing Test C_SUPPORTS_EXCEPTION
    -- Performing Test C_SUPPORTS_EXCEPTION - Success
    -- Performing Test CXX_SUPPORTS_EXCEPTION
    -- Performing Test CXX_SUPPORTS_EXCEPTION - Success
    -- Performing Test C_SUPPORTS_VISIBILITY
    -- Performing Test C_SUPPORTS_VISIBILITY - Success
    -- Performing Test CXX_SUPPORTS_VISIBILITY
    -- Performing Test CXX_SUPPORTS_VISIBILITY - Success
    -- Performing Test C_SUPPORTS_NO_EXPANSION_TO_DEFINED
    -- Performing Test C_SUPPORTS_NO_EXPANSION_TO_DEFINED - Success
    -- Performing Test CXX_SUPPORTS_NO_EXPANSION_TO_DEFINED
    -- Performing Test CXX_SUPPORTS_NO_EXPANSION_TO_DEFINED - Success
    -- Performing Test C_SUPPORTS_DIAGNOSTICS_COLOR
    -- Performing Test C_SUPPORTS_DIAGNOSTICS_COLOR - Success
    -- Performing Test CXX_SUPPORTS_DIAGNOSTICS_COLOR
    -- Performing Test CXX_SUPPORTS_DIAGNOSTICS_COLOR - Success
    -- Performing Test C_SUPPORTS_COLOR_DIAGNOSTICS
    -- Performing Test C_SUPPORTS_COLOR_DIAGNOSTICS - Failed
    -- Performing Test CXX_SUPPORTS_COLOR_DIAGNOSTICS
    -- Performing Test CXX_SUPPORTS_COLOR_DIAGNOSTICS - Failed
    -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
    -- Configuration Types:
    -- Build Types: Release
    -- Found PythonInterp: /home/wenzel/Projets/checksec.py/venv-pypy/bin/pypy3 (found suitable version "3.6.9", minimum required is "3.5")
    -- Found PythonLibs: python3.6
    -- Python version: 3.5
    -- Python lib:     python3.6
    -- Python include: /usr/lib/pypy3/include
    -- Python interpreter: /home/wenzel/Projets/checksec.py/venv-pypy/bin/pypy3
    -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED
    -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED - Success
    -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED
    -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED - Success
    -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS
    -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Success
    -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS
    -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Success
    -- Performing Test HAS_ANSI
    -- Performing Test HAS_ANSI - Success
    CMake Error at CMakeLists.txt:541 (add_subdirectory):
      add_subdirectory given source "/tmp/pip-install-nl285u7n/lief/package"
      which is not an existing directory.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-nl285u7n/lief/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-nl285u7n/lief/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nl285u7n/lief/setup.py", line 367, in <module>
        version=version
      File "/home/wenzel/Projets/checksec.py/venv-pypy/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/pypy3/lib-python/3/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/pypy3/lib-python/3/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/pypy3/lib-python/3/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/wenzel/Projets/checksec.py/venv-pypy/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/pypy3/lib-python/3/distutils/command/install.py", line 606, in run
        self.run_command('build')
      File "/usr/lib/pypy3/lib-python/3/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/pypy3/lib-python/3/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/pypy3/lib-python/3/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/pypy3/lib-python/3/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/pypy3/lib-python/3/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-nl285u7n/lief/setup.py", line 78, in run
        self.build_extension(ext)
      File "/tmp/pip-install-nl285u7n/lief/setup.py", line 202, in build_extension
        subprocess.check_call(configure_cmd, cwd=self.build_temp, env=env)
      File "/usr/lib/pypy3/lib-python/3/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-nl285u7n/lief', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-nl285u7n/lief/build', '-DPYTHON_EXECUTABLE=/home/wenzel/Projets/checksec.py/venv-pypy/bin/pypy3', '-DLIEF_PYTHON_API=on', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/wenzel/Projets/checksec.py/venv-pypy/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nl285u7n/lief/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nl285u7n/lief/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5nz6ls9h/install-record.txt --single-version-externally-managed --compile --install-headers /home/wenzel/Projets/checksec.py/venv-pypy/include/site/python3.6/lief Check the logs for full command output.
~~~

The Cmake error seems to be a missing directory.
~~~
    CMake Error at CMakeLists.txt:541 (add_subdirectory):
      add_subdirectory given source "/tmp/pip-install-nl285u7n/lief/package"
      which is not an existing directory.
~~~

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04
 - LIEF commit version: `0.10.1`

Thanks !

**Comment by romainthomas** [comment]
Could you try on the nightly package ?
```bash
$ pip install [--user] --index-url  https://lief-project.github.io/packages lief
```

**Comment by romainthomas** [comment]
It seems also being a duplication of #438

**Comment by Wenzel** [comment]
> Could you try on the nightly package ?

![Capture d’écran de 2020-10-04 18-55-39](https://user-images.githubusercontent.com/964610/95021758-41361080-0673-11eb-9cb7-9b9b3fc18919.png)

Not sure if you published a package on your Github registry ?
I can't see them.

![Capture d’écran de 2020-10-04 18-56-34](https://user-images.githubusercontent.com/964610/95021779-6034a280-0673-11eb-91b1-589ffee976f2.png)

**Comment by dmjh** [comment]
I solved the same problem by creating a package directory in the lief-0.10.1, and generating CMakeLists.txt inside the package dir. (Because I saw a CMake error saying that the source directory /home/user/lief-0.10.1/package does not contain a CMakeLists.txt file.)

**Comment by romainthomas** [comment]
Working with:
```bash
python -m pip install git+https://github.com/lief-project/LIEF.git
Collecting git+https://github.com/lief-project/LIEF.git
  Cloning https://github.com/lief-project/LIEF.git to /tmp/pip-req-build-pec9xekv
  Running command git clone -q https://github.com/lief-project/LIEF.git /tmp/pip-req-build-pec9xekv
Building wheels for collected packages: lief
  Building wheel for lief (setup.py) ... /
done
  Created wheel for lief: filename=lief-0.11.0.dev0-pp36-pypy36_pp73-linux_x86_64.whl size=2939513 sha256=e8e009ae0b7e2508d344b734b4388a62dbd2d05c227f460162b30b1dcbbe68c4
  Stored in directory: /tmp/pip-ephem-wheel-cache-58vwmf7z/wheels/31/57/dc/aa62900b330f156b83217f157f83ab461c5b51ce06df9f6c9a
Successfully built lief
Installing collected packages: lief
Successfully installed lief-0.11.0.dev0
```

**Comment by Gr3n1nj4** [comment]
![image](https://user-images.githubusercontent.com/121914734/236651252-ab3fd2c6-2541-4a87-8b03-cfa552d0e32b.png)
someone can help?
