### ISSUE TITLE
Can't Install LIEF on Python 3.9

### ISSUE THREAD

**Issue by Cy-Beard** [lief-project/LIEF#484]
On windows 10 laptop

pip install lief
OUTput
PS C:\Users\209892> pip install lief
Collecting lief
  Using cached lief-0.10.1.tar.gz (12.7 MB)
Building wheels for collected packages: lief
  Building wheel for lief (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\209892\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\209892\\AppData\\Local\\Temp\\pip-install-_5qxsavf\\lief\\setup.py'"'"'; __file__='"'"'C:\\Users\\209892\\AppData\\Local\\Temp\\pip-install-_5qxsavf\\lief\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\209892\AppData\Local\Temp\pip-wheel-lj7tyj47'
       cwd: C:\Users\209892\AppData\Local\Temp\pip-install-_5qxsavf\lief\
  Complete output (46 lines):
  0.10.1
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\209892\AppData\Local\Temp\pip-install-_5qxsavf\lief\setup.py", line 72, in run
      subprocess.check_output(['cmake', '--version'])
    File "c:\users\209892\appdata\local\programs\python\python39\lib\subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "c:\users\209892\appdata\local\programs\python\python39\lib\subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "c:\users\209892\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "c:\users\209892\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\209892\AppData\Local\Temp\pip-install-_5qxsavf\lief\setup.py", line 363, in <module>
      setup(
    File "c:\users\209892\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\209892\appdata\local\programs\python\python39\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\209892\AppData\Local\Temp\pip-install-_5qxsavf\lief\setup.py", line 74, in run
      raise RuntimeError("CMake must be installed to build the following extensions: " +
  RuntimeError: CMake must be installed to build the following extensions: lief
  ----------------------------------------
  ERROR: Failed building wheel for lief
  Running setup.py clean for lief
Failed to build lief
Installing collected packages: lief
    Running setup.py install for lief ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\209892\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\209892\\AppData\\Local\\Temp\\pip-install-_5qxsavf\\lief\\setup.py'"'"'; __file__='"'"'C:\\Users\\209892\\AppData\\Local\\Temp\\pip-install-_5qxsavf\\lief\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\209892\AppData\Local\Temp\pip-record-9o6dc4sy\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\209892\appdata\local\programs\python\python39\Include\lief'
         cwd: C:\Users\209892\AppData\Local\Temp\pip-install-_5qxsavf\lief\
    Complete output (48 lines):
    0.10.1
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\209892\AppData\Local\Temp\pip-install-_5qxsavf\lief\setup.py", line 72, in run
        subprocess.check_output(['cmake', '--version'])
      File "c:\users\209892\appdata\local\programs\python\python39\lib\subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "c:\users\209892\appdata\local\programs\python\python39\lib\subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\users\209892\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "c:\users\209892\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\209892\AppData\Local\Temp\pip-install-_5qxsavf\lief\setup.py", line 363, in <module>
        setup(
      File "c:\users\209892\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\209892\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\209892\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\209892\AppData\Local\Temp\pip-install-_5qxsavf\lief\setup.py", line 74, in run
        raise RuntimeError("CMake must be installed to build the following extensions: " +
    RuntimeError: CMake must be installed to build the following extensions: lief
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\209892\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\209892\\AppData\\Local\\Temp\\pip-install-_5qxsavf\\lief\\setup.py'"'"'; __file__='"'"'C:\\Users\\209892\\AppData\\Local\\Temp\\pip-install-_5qxsavf\\lief\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\209892\AppData\Local\Temp\pip-record-9o6dc4sy\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\209892\appdata\local\programs\python\python39\Include\lief' Check the logs for full command output.

If python 3.9 is not supported, is there a way to build it?

**Comment by romainthomas** [comment]
Please open a clean issue and first look at "Python 3.9" in the project you will get the answer

**Comment by Cy-Beard** [comment]
I may have fixed the issue.
ran:
pip install CMake
git cloned the LIEF repository into my Python39\site-packeges
cd to PYthon39\site-packeges\LIEF
python .\setup.py install
