### ISSUE TITLE
pip install lief not working on windows

### ISSUE THREAD

**Issue by newgre** [lief-project/LIEF#491]
**Describe the bug**
`pip install lief` produces an error on Windows 10 using python 3.9

**To Reproduce**
`pip install lief` from a terminal on Windows 10

**Expected behavior**
Successful installation of the lief python lib.

**Environment (please complete the following information):**
 - System and Version : Windows 10.0.19041

**Additional context**
```
c:\users\foo>pip install lief
Collecting lief
  Using cached lief-0.10.1.tar.gz (12.7 MB)
Using legacy 'setup.py install' for lief, since package 'wheel' is not installed.
Installing collected packages: lief
    Running setup.py install for lief ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\foo\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\foo\\AppData\\Local\\Temp\\pip-install-zug4oke4\\lief\\setup.py'"'"'; __file__='"'"'C:\\Users\\foo\\AppData\\Local\\Temp\\pip-install-zug4oke4\\lief\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\foo\AppData\Local\Temp\pip-record-8wpbttx_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\foo\appdata\local\programs\python\python39\Include\lief'
         cwd: c:\users\foo\AppData\Local\Temp\pip-install-zug4oke4\lief\
    Complete output (88 lines):
    0.10.1
    running install
    running build
    running build_ext
    cmake c:\users\foo\AppData\Local\Temp\pip-install-zug4oke4\lief -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=c:\users\foo\AppData\Local\Temp\pip-install-zug4oke4\lief\build\temp.win-amd64-3.9 -DPYTHON_EXECUTABLE=c:\users\foo\appdata\local\programs\python\python39\python.exe -DLIEF_PYTHON_API=on -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=c:\users\foo\AppData\Local\Temp\pip-install-zug4oke4\lief\build\temp.win-amd64-3.9 -DLIEF_USE_CRT_RELEASE=MT -A x64
    -- Building for: Visual Studio 16 2019
    -- LIEF_CRT: /MT
    -- Using Release VC++ CRT: MT
    -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
    -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
    -- The C compiler identification is MSVC 19.28.29333.0
    -- The CXX compiler identification is MSVC 19.28.29333.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- LIEF 0.10.0
    -- ccache: ON
    -- Enable JSON support
    -- Enable Frozen (C++14 support)
    -- Number of parallel compiler jobs set to /MP
    -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
    -- Configuration Types: Debug;Release;MinSizeRel;RelWithDebInfo
    -- Build Types: Release
    -- Found PythonInterp: C:/Users/foo/AppData/Local/Programs/Python/Python39/python.exe (found suitable version "3.9", minimum required is "3.5")
    -- Found PythonLibs: C:/Users/foo/AppData/Local/Programs/Python/Python39/libs/Python39.lib
    -- Python version: 3.5
    -- Python lib:     C:/Users/foo/AppData/Local/Programs/Python/Python39/libs/Python39.lib
    -- Python include: C:/Users/foo/AppData/Local/Programs/Python/Python39/include
    -- Python interpreter: C:/Users/foo/AppData/Local/Programs/Python/Python39/python.exe
    -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED
    -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED - Failed
    -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED
    -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED - Failed
    -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS
    -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Failed
    -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS
    -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Failed
    -- Performing Test HAS_ANSI
    -- Performing Test HAS_ANSI - Failed
    CMake Error at CMakeLists.txt:541 (add_subdirectory):
      add_subdirectory given source
      "C:/Users/foo/AppData/Local/Temp/pip-install-zug4oke4/lief/package" which
      is not an existing directory.


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/foo/AppData/Local/Temp/pip-install-zug4oke4/lief/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/foo/AppData/Local/Temp/pip-install-zug4oke4/lief/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\foo\AppData\Local\Temp\pip-install-zug4oke4\lief\setup.py", line 363, in <module>
        setup(
      File "c:\users\foo\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\foo\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\foo\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\foo\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\foo\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\foo\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\users\foo\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\foo\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\foo\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\foo\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\foo\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\foo\AppData\Local\Temp\pip-install-zug4oke4\lief\setup.py", line 78, in run
        self.build_extension(ext)
      File "c:\users\foo\AppData\Local\Temp\pip-install-zug4oke4\lief\setup.py", line 202, in build_extension
        subprocess.check_call(configure_cmd, cwd=self.build_temp, env=env)
      File "c:\users\foo\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\foo\\AppData\\Local\\Temp\\pip-install-zug4oke4\\lief', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\foo\\AppData\\Local\\Temp\\pip-install-zug4oke4\\lief\\build\\temp.win-amd64-3.9', '-DPYTHON_EXECUTABLE=c:\\users\\foo\\appdata\\local\\programs\\python\\python39\\python.exe', '-DLIEF_PYTHON_API=on', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\foo\\AppData\\Local\\Temp\\pip-install-zug4oke4\\lief\\build\\temp.win-amd64-3.9', '-DLIEF_USE_CRT_RELEASE=MT', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\foo\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\foo\\AppData\\Local\\Temp\\pip-install-zug4oke4\\lief\\setup.py'"'"'; __file__='"'"'C:\\Users\\foo\\AppData\\Local\\Temp\\pip-install-zug4oke4\\lief\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\foo\AppData\Local\Temp\pip-record-8wpbttx_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\foo\appdata\local\programs\python\python39\Include\lief' Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'c:\users\foo\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.
```

**Comment by romainthomas** [comment]
Resolved with master branch

**Comment by newgre** [comment]
Any way to get `pip install lief` to work at all on Windows?
The documentation says to use `pip install --index-url  https://lief-project.github.io/packages lief` to get the nightly build - but that doesn't work either:

```
Looking in indexes: https://lief-project.github.io/packages/lief
ERROR: Could not find a version that satisfies the requirement lief (from versions: none)
ERROR: No matching distribution found for lief
```

**Comment by romainthomas** [comment]
There still some issues with Appveyor CI: the image VS 2019 supports Python 3.9 but breaks ssh. Therefore, I would recommend to install from sources:

```bash
$ git clone --depth 1 -j3 https://github.com/lief-project/LIEF.git
$ python ./setup install [--user]
```
