### ISSUE TITLE
Unable to open PE file with utf-8 names in python [Windows]

### ISSUE THREAD

**Issue by marcelotduarte** [lief-project/LIEF#653]
**Describe the bug**
In Windows, I have files with utf8 names, like "ação.exe". LIEF returns: Unable to open the file 'ação.exe'
But I can read it in raw mode using lief.PE.parse.

**To Reproduce**
Make a copy of cmd.exe to ação.exe
```
python
>>> import lief
>>> lief.parse("ação.exe")
Unable to open the file 'ação.exe'
Unable to open the file 'ação.exe'
Unable to open the file!
Unable to open the 'ação.exe'
Unknown format
>>> lief.PE.parse("ação.exe")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
lief.bad_file: Unable to open ação.exe
>>> with open("ação.exe", "rb") as raw: lief.parse(raw, name="ação.exe")
...
 is not an ELF
<lief.PE.Binary object at 0x0000020867898030>
>>> with open("ação.exe", "rb") as raw: lief.PE.parse(raw, name="ação.exe")
...
<lief.PE.Binary object at 0x00000208678825F0>
```
**Expected behavior**
Open the file without errors.

**Environment (please complete the following information):**
 - System and Version : [e.g. Ubuntu 16.04] Windows 10
 - Target format (PE, ELF, Mach-O) PE
 - LIEF commit version: 0.11.5-551ede5 and 0.12.0-cb34da9

**Additional context**
Under Linux, this doesn't happen.

**Comment by romainthomas** [comment]
LIEF `parse()` functions accept a `os.PathLike` so this can be closed

**Comment by marcelotduarte** [comment]
The error persists with lief 0.15.1:
```python
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
>>> lief.__version__
'0.15.1-'
>>> lief.parse("ação.exe")
Can't open 'ação.exe'
Can't open 'ação.exe'
Can't open 'ação.exe'
Can't open 'ação.exe'
Unknown format
>>> from pathlib import Path
>>> lief.parse(Path("ação.exe"))
Can't open 'ação.exe'
Can't open 'ação.exe'
Can't open 'ação.exe'
Can't open 'ação.exe'
Unknown format
>>> lief.PE.parse("ação.exe")
Can't open 'ação.exe'
>>> lief.PE.parse(Path("ação.exe"))
Can't open 'ação.exe'
>>> with open("ação.exe", "rb") as raw: lief.PE.parse(raw, name="ação.exe")
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: parse(): incompatible function arguments. The following argument types are supported:
    1. parse(filename: str, config: lief._lief.PE.ParserConfig = <lief._lief.PE.ParserConfig object at 0x00007FFFFEF5F390>) -> Optional[lief
._lief.PE.Binary]
    2. parse(raw: list[int], config: lief._lief.PE.ParserConfig = <lief._lief.PE.ParserConfig object at 0x00007FFFFEF5F3B0>) -> Optional[lie
f._lief.PE.Binary]
    3. parse(obj: Union[io.IOBase | os.PathLike], config: lief._lief.PE.ParserConfig = <lief._lief.PE.ParserConfig object at 0x00007FFFFEF5F
3D0>) -> Optional[lief._lief.PE.Binary]

Invoked with types: BufferedReader, kwargs = { name: str }
>>>
```
