### ISSUE TITLE
While installing : pip install lief, shows error, Please help urgently , as lief dependency requires for flare-capa

### ISSUE THREAD

**Issue by rohitse914** [lief-project/LIEF#656]
Building wheels for collected packages: lief
  Building wheel for lief (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\test_computer\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\setup.py'"'"'; __file__='"'"'C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\test_computer\AppData\Local\Temp\pip-wheel-8w9x8s46'
       cwd: C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\
  Complete output (57 lines):
  0.11.5
  running bdist_wheel
  running build
  running build_ext
  Platform: Windows
  Wheel library: lief
  cmake C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05 -DLIEF_FORCE_API_EXPORTS=ON -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\build\temp.win-amd64-3.10 -DPYTHON_EXECUTABLE=C:\Users\test_computer\AppData\Local\Programs\Python\Python310\python.exe -DLIEF_PYTHON_API=on -DLIEF_LOGGING_DEBUG=off -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\build\temp.win-amd64-3.10 -DLIEF_USE_CRT_RELEASE=MT -A x64
  -- Building for: NMake Makefiles
  -- LIEF_CRT: /MT
  -- Using Release VC++ CRT: MT
  CMake Error at CMakeLists.txt:30 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.

  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/test_computer/AppData/Local/Temp/pip-install-znc30aqa/lief_c9faf5a7de54449a93cad416b3cc2b05/build/temp.win-amd64-3.10/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\setup.py", line 455, in <module>
      setup(
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\setup.py", line 87, in run
      self.build_extension(ext)
    File "C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\setup.py", line 232, in build_extension
      subprocess.check_call(configure_cmd, cwd=self.build_temp, env=env)
    File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05', '-DLIEF_FORCE_API_EXPORTS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\build\\temp.win-amd64-3.10', '-DPYTHON_EXECUTABLE=C:\\Users\\test_computer\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-DLIEF_PYTHON_API=on', '-DLIEF_LOGGING_DEBUG=off', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\build\\temp.win-amd64-3.10', '-DLIEF_USE_CRT_RELEASE=MT', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for lief
  Running setup.py clean for lief
Failed to build lief
Installing collected packages: lief
    Running setup.py install for lief ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\test_computer\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\setup.py'"'"'; __file__='"'"'C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\test_computer\AppData\Local\Temp\pip-record-bnlv3uej\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\test_computer\AppData\Local\Programs\Python\Python310\Include\lief'
         cwd: C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\
    Complete output (59 lines):
    0.11.5
    running install
    running build
    running build_ext
    Platform: Windows
    Wheel library: lief
    cmake C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05 -DLIEF_FORCE_API_EXPORTS=ON -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\build\temp.win-amd64-3.10 -DPYTHON_EXECUTABLE=C:\Users\test_computer\AppData\Local\Programs\Python\Python310\python.exe -DLIEF_PYTHON_API=on -DLIEF_LOGGING_DEBUG=off -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\build\temp.win-amd64-3.10 -DLIEF_USE_CRT_RELEASE=MT -A x64
    -- Building for: NMake Makefiles
    -- LIEF_CRT: /MT
    -- Using Release VC++ CRT: MT
    CMake Error at CMakeLists.txt:30 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.

    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/test_computer/AppData/Local/Temp/pip-install-znc30aqa/lief_c9faf5a7de54449a93cad416b3cc2b05/build/temp.win-amd64-3.10/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\setup.py", line 455, in <module>
        setup(
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\command\install.py", line 568, in run
        self.run_command('build')
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\setup.py", line 87, in run
        self.build_extension(ext)
      File "C:\Users\test_computer\AppData\Local\Temp\pip-install-znc30aqa\lief_c9faf5a7de54449a93cad416b3cc2b05\setup.py", line 232, in build_extension
        subprocess.check_call(configure_cmd, cwd=self.build_temp, env=env)
      File "C:\Users\test_computer\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05', '-DLIEF_FORCE_API_EXPORTS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\build\\temp.win-amd64-3.10', '-DPYTHON_EXECUTABLE=C:\\Users\\test_computer\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-DLIEF_PYTHON_API=on', '-DLIEF_LOGGING_DEBUG=off', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\build\\temp.win-amd64-3.10', '-DLIEF_USE_CRT_RELEASE=MT', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\test_computer\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\setup.py'"'"'; __file__='"'"'C:\\Users\\test_computer\\AppData\\Local\\Temp\\pip-install-znc30aqa\\lief_c9faf5a7de54449a93cad416b3cc2b05\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\test_computer\AppData\Local\Temp\pip-record-bnlv3uej\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\test_computer\AppData\Local\Programs\Python\Python310\Include\lief' Check the logs for full command output.

**Comment by rohitse914** [comment]
I found the issue , when I run it on 32 bit machine it successfully but in x64 machine it fails to install due lief 32bit dependency
