### ISSUE TITLE
Test LIEF on radare2 test suite

### ISSUE THREAD

**Issue by romainthomas** [lief-project/LIEF#7]
Binaries are available here: https://github.com/radare/radare2-regressions/tree/master/bins

**Comment by insomniacslk** [comment]
Also failing on the `tiny.bin` as found at http://www.muppetlabs.com/~breadbox/software/tiny/teensy.html 

```
$ python3.6
Python 3.6.0b2 (default, Oct 11 2016, 05:27:10) 
[GCC 6.2.0 20161005] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
>>> lief.parse('tiny')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
lief.read_out_of_bound: Offset: 0xc0312ab3 is bigger than the binary size
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
lief.read_out_of_bound: Offset: 0xc0312ab3 is bigger than the binary size
```

**Comment by romainthomas** [comment]
@insomniacslk  Now ``tiny.bin`` is supported.

**Comment by romainthomas** [comment]
All radare2 tests cases are handle by LIEF (except the endianess. See: #74)
