### ISSUE TITLE
LIEF Install failed with latest setuptools

### ISSUE THREAD

**Issue by ktiays** [lief-project/LIEF#783]
I install LIEF by ```pip``` with python 3.10, but I got an error.

I was already upgraded the pip and setuptools to the latest version, but it didn't work.

There is my log:
```
❯ python -m pip install lief
Collecting lief
  Using cached lief-0.12.1.zip (15.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/f1/pt8456l54hv_yp24rp9nb37h0000gn/T/pip-install-oljeitus/lief_a6d8531d95734f399f46559964bb95ca/setup.py", line 12, in <module>
          from setuptools.command.build_ext import build_ext, copy_file
      ImportError: cannot import name 'copy_file' from 'setuptools.command.build_ext' (/opt/homebrew/lib/python3.10/site-packages/setuptools/command/build_ext.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
## System Version
macOS 13.0 Beta 7

## Software Version
python 3.10
pip 22.2.2
setuptools 65.3.0

**Comment by romainthomas** [comment]
Duplicated with #770. I'll publish a new patch release though (0.12.2)
