### ISSUE TITLE
[Bug] Poetry install fails on m1 macOS w/ Python 3.10.8 : pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by Mikaayenson** [lief-project/LIEF#827]
**Describe the bug**

When running `poetry add lief` the install fails with error:
- `Failed to install /Users/stryker/Library/Caches/pypoetry/artifacts/df/63/66/6a11a7b68bd898975dde9d9f04d9d5b1b8ff582f622e0731c7e0857d29/lief-0.12.3.zip` (assuming no wheel exists (e.g. `lief-0.12.3-cp310-cp310-macosx_12_0_arm64.whl`))
- Note: `pip install lief` will still build a wheel from zip 

**To Reproduce**
- run `poetry add lief` on Python 3.10.8 with m1 macOS

**Expected behavior**

- Should be able to install lief 

**Environment (please complete the following information):**
 - System and Version : Darwin
 - Python Version: 3.10.8

**Additional context**

<details>

<summary> Command Line Output </summary>

```bash

➜  poetry add lief
Using version ^0.12.3 for lief

Updating dependencies
Resolving dependencies... (0.4s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing lief (0.12.3): Failed

  CalledProcessError

  Command '['/Users/username/Library/Caches/pypoetry/virtualenvs/rotten-apple-_VKEqfAO-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/username/Library/Caches/pypoetry/virtualenvs/rotten-apple-_VKEqfAO-py3.10', '--no-deps', '/Users/username/Library/Caches/pypoetry/artifacts/df/63/66/6a11a7b68bd898975dde9d9f04d9d5b1b8ff582f622e0731c7e0857d29/lief-0.12.3.zip']' returned non-zero exit status 1.

  at /opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py:526 in run
       522│             # We don't call process.wait() as .__exit__ does that for us.
       523│             raise
       524│         retcode = process.poll()
       525│         if check and retcode:
    →  526│             raise CalledProcessError(retcode, process.args,
       527│                                      output=stdout, stderr=stderr)
       528│     return CompletedProcess(process.args, retcode, stdout, stderr)
       529│
       530│

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/username/Library/Caches/pypoetry/virtualenvs/rotten-apple-_VKEqfAO-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/username/Library/Caches/pypoetry/virtualenvs/rotten-apple-_VKEqfAO-py3.10', '--no-deps', '/Users/username/Library/Caches/pypoetry/artifacts/df/63/66/6a11a7b68bd898975dde9d9f04d9d5b1b8ff582f622e0731c7e0857d29/lief-0.12.3.zip'] errored with the following return code 1, and output:
  Processing /Users/username/Library/Caches/pypoetry/artifacts/df/63/66/6a11a7b68bd898975dde9d9f04d9d5b1b8ff582f622e0731c7e0857d29/lief-0.12.3.zip
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [28 lines of output]
        <string>:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        Traceback (most recent call last):
          File "/Users/username/Library/Caches/pypoetry/virtualenvs/rotten-apple-_VKEqfAO-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
            main()
          File "/Users/username/Library/Caches/pypoetry/virtualenvs/rotten-apple-_VKEqfAO-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/Users/username/Library/Caches/pypoetry/virtualenvs/rotten-apple-_VKEqfAO-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/private/var/folders/ng/zlptgm9552j2dhj_xzy0r32h0000gn/T/pip-build-env-ats313la/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/private/var/folders/ng/zlptgm9552j2dhj_xzy0r32h0000gn/T/pip-build-env-ats313la/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
            self.run_setup()
          File "/private/var/folders/ng/zlptgm9552j2dhj_xzy0r32h0000gn/T/pip-build-env-ats313la/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/private/var/folders/ng/zlptgm9552j2dhj_xzy0r32h0000gn/T/pip-build-env-ats313la/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 478, in <module>
          File "<string>", line 474, in get_version
          File "<string>", line 453, in get_pkg_info_version
          File "/private/var/folders/ng/zlptgm9552j2dhj_xzy0r32h0000gn/T/pip-build-env-ats313la/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
            dist = get_provider(dist)
          File "/private/var/folders/ng/zlptgm9552j2dhj_xzy0r32h0000gn/T/pip-build-env-ats313la/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 354, in get_provider
            return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
          File "/private/var/folders/ng/zlptgm9552j2dhj_xzy0r32h0000gn/T/pip-build-env-ats313la/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
            needed = self.resolve(parse_requirements(requirements))
          File "/private/var/folders/ng/zlptgm9552j2dhj_xzy0r32h0000gn/T/pip-build-env-ats313la/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
            raise DistributionNotFound(req, requirers)
        pkg_resources.DistributionNotFound: The 'lief' distribution was not found and is required by the application
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.


  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│
      1478│         return decode(output)
      1479│
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /Users/username/Library/Caches/pypoetry/artifacts/df/63/66/6a11a7b68bd898975dde9d9f04d9d5b1b8ff582f622e0731c7e0857d29/lief-0.12.3.zip

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│
```

**Comment by romainthomas** [comment]
Hello @Mikaayenson 
As mentioned in the issue #778, there is not current support for Apple M1 in the Github Action CI. That's why the wheel does not exist.
