### ISSUE TITLE
Null pointer checks in the C API

### ISSUE THREAD

**Issue by liyansong2018** [lief-project/LIEF#835]
**Describe the bug**
:) Hello, when I first used LIEF, I found that although Parse::parse(file) determines whether the input file can be opened, it still cites a null pointer from virutual file.

Bug
```c
void init_c_binary(Elf_Binary_t* c_binary, Binary* binary) {
  c_binary->handler     = reinterpret_cast<void*>(binary);
  c_binary->name        = binary->name().c_str();	// null pointer dereference!
  c_binary->type        = static_cast<enum LIEF_ELF_ELF_CLASS>(binary->type());
  c_binary->interpreter = nullptr;
```

**To Reproduce**
```shell
# # non-existent file
$ ./elf_reader abc  
Can't open 'abc'
zsh: segmentation fault  ./elf_reader abc
```

**Expected behavior**
Normal exit

**Environment (please complete the following information):**
 - System and Version : [e.g. Kali 2020.4]
 - Target format (ELF)
 - LIEF commit version: lastest

**Additional context**
```shell
Program received signal SIGSEGV, Segmentation fault.
gef➤  bt
#0  0x00007ffff7ed1fc4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const () from /lib/x86_64-linux-gnu/libstdc++.so.6                                         
#1  0x00005555555a4ad3 in LIEF::ELF::init_c_binary (c_binary=0x555555e6f3e0, binary=0x0) at /home/lys/Tools/LIEF/api/c/ELF/Binary.cpp:39                                                                      
#2  0x00005555555a4cda in elf_parse (file=0x7fffffffe406 "abc") at /home/lys/Tools/LIEF/api/c/ELF/Binary.cpp:70                                                                                                
#3  0x00005555555a40f8 in main ()
```

**Comment by romainthomas** [comment]
Thank you for the issue/PR.
