### ISSUE TITLE
[Python|PE] UTF-8 encoding

### ISSUE THREAD

**Issue by ner0x652** [lief-project/LIEF#85]
Here's my short script
```Python
#!/usr/bin/env python3

import lief
import sys


def show_exports(dll):
    if dll.has_exports:
        for e in dll.exported_functions:
            print(e)
    else:
        print("{0} {1}".format(dll.name, "has no exports"))


def comes_act():
    if len(sys.argv) < 2:
        print("[USAGE]: {0} <executable>".format(sys.argv[0]))
        sys.exit(1)

    try:
        dll = lief.PE.parse(sys.argv[1])
    except lief.bad_format as err:
        print("Error: {0}".format(err))
        sys.exit(1)

    show_exports(dll)


if __name__ == "__main__":
    comes_act()
```
And the traceback
```Python
Traceback (most recent call last):
  File "comes.py", line 30, in <module>
    comes_act()
  File "comes.py", line 26, in comes_act
    show_exports(dll)
  File "comes.py", line 9, in show_exports
    for e in dll.exported_functions:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

The trouble is that I haven't found a solution to address this issue. Nobody I asked help from was able to understand... do you know if I'm wrong or maybe it's an issue somewhere else than in the script's code?

Thank you!

**Comment by romainthomas** [comment]
Hi @ner0x652 
Could you check if https://github.com/lief-project/LIEF/commit/c13d0c54fee914adf6b0fabc99801fd517e2d559 fix your issue ? (branch ``fix/85``)

**Comment by ner0x652** [comment]
Hi. I'll check in 4-5 hours, after I get back to the computer. Thank you!

**Comment by ner0x652** [comment]
All good, the issue is solved. Thank you!
