### ISSUE TITLE
ImportError: cannot import name '_lief' from partially initialized module 'lief'

### ISSUE THREAD

**Issue by ppetr** [lief-project/LIEF#920]
I was installing `appimage-builder`, which depends on `lief`:

```
$ sudo pip3 install appimage-builder
...
Collecting lief                                                                                                                                                                                 
  Downloading lief-0.13.0-cp39-cp39-manylinux2014_aarch64.whl (4.2 MB)
...
```

But when attempting to run the main program, importing `lief` crashes with:

```
$ appimage-builder --help                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                              
  File "/usr/local/bin/appimage-builder", line 5, in <module>                                                                                                                                   
    from appimagebuilder.__main__ import __main__                                                                                                                                               
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/__main__.py", line 20, in <module>                                                                                               
    from appimagebuilder.invoker import Invoker                                                                                                                                                 
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/invoker.py", line 14, in <module>                                                                                                
    from appimagebuilder.commands.command import Command                                                                                                                                        
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/commands/__init__.py", line 15, in <module>                                                                                      
    from .create_appimage import CreateAppImageCommand                                                                                                                                          
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/commands/create_appimage.py", line 13, in <module>                                                                               
    from appimagebuilder.modules.prime import AppImagePrimer                                                                                                                                    
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/modules/prime/__init__.py", line 13, in <module>                                                                                 
    from .appimage_primer import AppImagePrimer                                                                                                                                                 
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/modules/prime/appimage_primer.py", line 22, in <module>                                                                          
    import lief                                                                                                                                                                                 
  File "/usr/local/lib/python3.9/dist-packages/lief/__init__.py", line 2, in <module>                                                                                                           
    from . import _lief                                                                                                                                                                         
ImportError: cannot import name '_lief' from partially initialized module 'lief' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/lief/__init__.py)
```

Which apparently points to https://github.com/lief-project/LIEF/blob/966a66c78a498ed694f28a25b350853852612c4d/api/python/lief/__init__.py#L2

I'm running Debian GNU/Linux 11 on aarch64, 6.1.21-v8+.

Thank you for your help!

**Comment by romainthomas** [comment]
Thank you @ppetr for raising this issue. The root cause is the same as: https://github.com/lief-project/LIEF/issues/901 and I'll create a patch release `0.13.1` soon.
